language: java
script: mvn install

cache:
  directories:
  - .autoconf
  - $HOME/.m2

before_install:
- chmod +x ./etc/before.sh
- ./etc/before.sh

deploy:
  skip_cleanup: true
  provider: script
  script: mvn deploy
  on:
    branch: master